Activity/discussion/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('todolist/', include('todolist.urls')),
    path('admin/', admin.site.urls),
]

Activity/todolist/urls.py
from django.urls import path
from . import views

# Syntax
# path(route, view, name)
app_name = 'todolist'
urlpatterns = [
	# /todolist route
	path('', views.index, name='index'),
	path('register', views.register, name="register"),
	path('change_password', views.change_password, name="change_password"),
	path('login', views.login_view, name="login"),
	path('logout', views.logout_view, name="logout"),
	path('add_task', views.add_task, name="add_task"),
	path('<int:todoitem_id>/', views.todoitem, name='viewtodoitem'),
	path('<int:todoitem_id>/edit', views.update_task, name='update_task'),
	path('<int:todoitem_id>/delete', views.delete_task, name="delete_task"),
]

Activity/todolist/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.

class ToDoItem(models.Model):
	task_name = models.CharField(max_length=50)
	description = models.CharField(max_length=200)
	status = models.CharField(max_length=50, default="pending")
	date_created = models.DateTimeField('date created')
	user = models.ForeignKey(User, on_delete=models.CASCADE, default="")

Activity/todolist/forms.py
from django import forms

class LoginForm(forms.Form):
	username = forms.CharField(label='Username', max_length=20)
	password = forms.CharField(label='Password', max_length=20)

class AddTaskForm(forms.Form):
	task_name = forms.CharField(label='Task Name', max_length=50)
	description = forms.CharField(label='Description', max_length=200)

class UpdateTaskForm(forms.Form):
	task_name = forms.CharField(label='Task Name', max_length=50)
	description = forms.CharField(label='Description', max_length=200)
	status = forms.CharField(label='Status', max_length=50)

class RegisterForm(forms.Form):
	username = forms.CharField(label='Username', max_length=20)
	first_name = forms.CharField(label='First Name', max_length=20)
	last_name = forms.CharField(label='Last Name', max_length=20)
	email = forms.CharField(label='Email', max_length=20)
	password = forms.CharField(label='Password', max_length=20)
	confirm_password = forms.CharField(label='Confirm Password', max_length=20)

Activity/todolist/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.http import HttpResponse
# from django.template import loader
from django.contrib.auth.models import User
from django.contrib.auth import authenticate, login, logout
from django.forms.models import model_to_dict
from django.utils import timezone

# Local Imports
from .models import ToDoItem
from .forms import LoginForm, AddTaskForm, UpdateTaskForm, RegisterForm

def index(request):
	# todoitem_list = ToDoItem.objects.all()
	todoitem_list = ToDoItem.objects.filter(user_id=request.user.id)

	context = {'todoitem_list': todoitem_list,
			   'user': request.user}
			   
	return render(request, "todolist/index.html", context)

def todoitem(request, todoitem_id):
	todoitem = get_object_or_404(ToDoItem, pk=todoitem_id)
	context = {'todoitem': todoitem}
	return render(request, "todolist/todoitem.html", context)

def register(request):
    context = {}

    if request.method == 'POST':
        form = RegisterForm(request.POST)

        if form.is_valid() == False:
            form = RegisterForm()
            context['form'] = form
            print('Form not valid')
        else:
            username = form.cleaned_data['username']
            first_name = form.cleaned_data['first_name']
            last_name = form.cleaned_data['last_name']
            email = form.cleaned_data['email']
            password = form.cleaned_data['password']
            confirm_password = form.cleaned_data['confirm_password']

            if User.objects.filter(username=username).exists() and password == confirm_password:
               	print('Username is already taken')
            else:
                user = User.objects.create_user(username=username,email=email,password=password,first_name=first_name,last_name=last_name)
                user.save()
    else:
        form = RegisterForm()
        context['form'] = form

    return render(request, "todolist/register.html", context)


def change_password(request):
	is_user_authenticated = False

	user = authenticate(username="johndoe", password="johndoe1")
	print(user)

	if user is not None:
		authenticated_user = User.objects.get(username='johndoe')
		authenticated_user.set_password("johndoe1")
		authenticated_user.save()
		is_user_authenticated = True

	context = {
		"is_user_authenticated": is_user_authenticated
	}

	return render(request, "todolist/change_password.html", context)

def login_view(request):
    context = {}

    if request.method == 'POST':
        form = LoginForm(request.POST)

        if form.is_valid():
            username = form.cleaned_data['username']
            password = form.cleaned_data['password']
            user = authenticate(username=username, password=password)

            if user is not None:
                login(request, user)
                return redirect("todolist:index")
            else:
                context['error'] = True
        else:
            context['form'] = form
    else:
        form = LoginForm()
        context['form'] = form

    return render(request, "todolist/login.html", context)

def logout_view(request):
	logout(request)
	return redirect("todolist:index")

def add_task(request):
	context = {}

	if request.method == 'POST':
		form = AddTaskForm(request.POST)

		if form.is_valid() == False:
			form = AddTaskForm()

		else:
			task_name = form.cleaned_data['task_name']
			description = form.cleaned_data['description']

			duplicates = ToDoItem.objects.filter(task_name=task_name)

			if not duplicates:
				ToDoItem.objects.create(task_name=task_name, description=description, date_created=timezone.now(), user_id=request.user.id)

				return redirect("todolist:index")

			else:
				context = {
					"error": True
				}
	return render(request, "todolist/add_task.html", context)

def update_task(request, todoitem_id):
	todoitem = ToDoItem.objects.filter(pk=todoitem_id)

	context = {
		"user": request.user,
		"todoitem_id": todoitem_id,
		"task_name": todoitem[0].task_name,
		"description": todoitem[0].description,
		"status": todoitem[0].status
	}

	if request.method == 'POST':
		form = UpdateTaskForm(request.POST)

		if form.is_valid() == False:
			form = UpdateTaskForm()

		else:
			task_name = form.cleaned_data['task_name']
			description = form.cleaned_data['description']
			status = form.cleaned_data['status']

			if todoitem:
				todoitem[0].task_name = task_name
				todoitem[0].description = description
				todoitem[0].status = status

				todoitem[0].save()

				return redirect("todolist:index")

			else:
				context = {
					"error": True
				}
	return render(request, "todolist/add_task.html", context)

def delete_task(request, todoitem_id):
	todoitem = ToDoItem.objects.filter(pk=todoitem_id).delete()
	return redirect("todolist:index")

Activity/templates/base.html
<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<title>{% block title %}To Do App{% endblock %}</title>

	<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">

</head>
<body>
	{% include "navbar.html" %}	
	{% block content %}
	{% endblock %}

	<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">

</body>
</html>

Activity/templates/navbar.html
<nav class="navbar navbar-dark bg-dark">
  <div class="container-fluid">
    <a class="navbar-brand" href="#">To Do List</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse " id="navbarNav">
      <ul class="navbar-nav ms-auto">
        <li class="nav-item">
          <a class="nav-link" href="{% url 'todolist:index' %}">Home</a>
        </li>
        <li class="nav-item" id="add_nav">
          <a class="nav-link" href="{% url 'todolist:add_task' %}">Add Task</a>
        </li>
        <li class="nav-item" id="login_nav">
          <a class="nav-link" href="login">Login</a>
        </li>
        <li class="nav-item" id="regi_nav">
          <a class="nav-link" href="register">Register</a>
        </li>
        <li class="nav-item" id="logout_nav">
          <a class="nav-link" href="{% url 'todolist:logout' %}">Logout</a>
        </li>
      </ul>
    </div>
  </div>
</nav>

Activity/todolist/templates/todolist/add_task.html
{% extends 'base.html' %}

{% block title %}Login{% endblock %}

{% block content %}
<div class="container">
	<div class="row">
		<div class="col-6 offset-3">
			<h1 class="text-center my-3">Add A Task</h1>
			{% if error == True %}
				<p class="text-danger">Duplicate task found</p>
			{% endif %}
			<form action="{% url 'todolist:add_task' %}" method="post">
				{% csrf_token %}
				<div class="mb-3">
					<label for="task_name">Task Name: </label>
					<input class="form-control" id="task_name" type="text" name="task_name" value="{{ task_name }}" maxlength="50" required>
				</div>
				<div class="mb-3">
					<label for="description">Description: </label>
					<textarea class="form-control" id="description" type="text" name="description" value="{{ description }}" required></textarea>
				</div>
				<div class="text-center d-grid gap-1">
					<input class="btn btn-success" type="submit" value="Add Task">
				</div>
			</form>
		</div>
	</div>
</div>
{% endblock %}

Activity/todolist/templates/todolist/change_password.html
{% if is_user_authenticated == False %}
	<h1>Invalid User Credentials</h1>
	<p>Check if the username and password is correct</p>
{% else %}
	<h1>User Password Successfully Updated!</h1>
	<p>The password has been successfully updated.</p>
	
{% endif %}

Activity/todolist/templates/todolist/index.html
{% extends 'base.html' %}

{% block title %}Home{% endblock %}

{% block content %}
	<div class="container">
			<div class="header">
				{% if todoitem_list and user.is_anonymous == False %}
              <h1 style="" class="text-center my-4">Welcome {{ user.first_name }} {{ user.last_name }}!</h1>
            </div>

			<div class="row d-flex justify-content-center" style="width: 30%;">

					<table class="table table-bordered table-condensed text-center">
						<thead style="background-color: black;color: white;font-size: 20px;">
							<tr>
								<th class="col-5">My Tasks</th>
							</tr>
						</thead>
						<tbody>
							<tr>
								<!-- TASK -->
								{% if todoitem_list %}
									<td>
										{% for todoitem in todoitem_list %}
										<li class="list-group-item">
											<a href="{% url 'todolist:viewtodoitem' todoitem.id %}" class="text-decoration-none">
												{{ todoitem.task_name }}
											</a>
										</li>
										{% endfor %}
									</td>
								{% else %}
									<td>
										<p class="text-center my-3">No tasks have been created.</p>
									</td>
								{% endif %}
							</tr>
						</tbody>
					</table>
				</div>
			</div>
		</div>
	
	{% elif user.is_anonymous == True %}
		<h1 class="text-center my-3">You are not authorized to access this page</h1>
		<p class="text-center">Kindly login<a href="{% url 'todolist:login' %}">here</a></p>

	{% else %}
		<p class="text-center">No tasks have been created.</p>

	{% endif %}
{% endblock %}

Activity/todolist/templates/todolist/login.html
{% extends 'base.html' %}

{% block title %}Login{% endblock %}

{% block content %}
<div class="container">
	<div class="row">
		<div class="col-6 offset-3">
			<h1 class="text-center my-3">Login</h1>
			{% if error == True %}
				<p class="text-danger">Invalid user credentials. please check your username and password</p>
			{% endif %}
			<form action="{% url 'todolist:login' %}" method="post">
				{% csrf_token %}
				<div class="mb-3">
				<label for="username">Username: </label>
					<input class="form-control" id="username" type="text" name="username" value="{{ username }}" maxlength="20" required>
				</div>
				<div class="mb-3">
				<label for="password">Password: </label>
					<input class="form-control" id="password" type="password" name="password" value="{{ password }}" maxlength="20" required>
				</div>
				<div class="text-center d-grid gap-1">
					<input class="btn btn-success" type="submit" value="Login">
				</div>
			</form>
		</div>
 	</div>
</div>
{% endblock %}

Activity/todolist/templates/todolist/register.html
{% extends 'base.html' %}

{% block title %}Register{% endblock %}

{% block content %}
<div class="container">
	<div class="row">
		<div class="col-6 offset-3">
			<h1 class="text-center my-3">Register</h1>
			{% if error == True %}
				<p class="text-danger">User already exists. Please change your username and password</p>
			{% endif %}
			<form action="{% url 'todolist:register' %}" method="post">
				{% csrf_token %}

				<div class="mb-3">
					<label for="username">Username: </label>
					<input class="form-control" id="username" type="text" name="username" value="{{ username }}" maxlength="20" required>
				</div>

				<div class="mb-3">
					<label for="first_name">First Name: </label>
					<input class="form-control" id="first_name" type="text" name="first_name" value="{{ first_name }}" maxlength="20" required>
				</div>

				<div class="mb-3">
					<label for="last_name">Last Name: </label>
					<input class="form-control" id="last_name" type="text" name="last_name" value="{{ last_name }}" maxlength="20" required>
				</div>

				<div class="mb-3">
					<label for="email">Email: </label>
					<input class="form-control" name="email" type="email" value="{{ email }}" maxlength="50" required>
				</div>

				<div class="mb-3">
					<label for="password">Password: </label>
					<input class="form-control" id="password" type="text" name="password" value="{{ password }}" maxlength="50" required>
				</div>

				<div class="mb-3">
					<label for="confirm_password">Password: </label>
					<input class="form-control" id="confirm_password" type="text" name="confirm_password" value="{{ confirm_password }}" maxlength="50" required>
				</div>

				<div class="text-center">
					<input class="btn btn-success" type="submit" value="Register">
				</div>
			</form>
		</div>
 	</div>
</div>
{% endblock %}

Activity/todolist/templates/todolist/todoitem.html
{% extends 'base.html' %}

{% block title %}Login{% endblock %}

{% block content %}
<div class="container my-5">
	<div class="row d-flex justify-content-center">
		<div class="col-5">
			<div class="mx-auto">
				<div class="card">
					<h1 class="card-header text-center" style="background-color: black;color: white;font-size: 40px;"> {{ task_name }} </h1>
					<div class="card-body">
						<h5 class="card-title text-center"><b>Status</b></h5>
						<h6 class="text-center">{{ status }} </h6>
						<p class="card-text text-center">Description: {{ description }}</p>
					</div>
					<div class="card-footer p-2 text-center">
						<div class="row">
							<div class="col-4 d-grid gap-1">
								<button class="btn btn-success mx-1 text-decoration-none">
									<a href="{% url 'todolist:update_task' todoitem.id %}" class="text-light text-decoration-none">
										Edit Task
									</a>
								</button>
							</div>
							<div class="col-4 d-grid gap-1">
								<button class="btn btn-warning mx-1 text-decoration-none">
									<a href="{% url 'todolist:delete_task' todoitem.id %}" class="text-light text-decoration-none">
										Delete Task
									</a>
								</button>
							</div>
							<div class="col-4 d-grid gap-1">
								<button class="btn btn-danger mx-1 text-decoration-none">
									<a href="{% url 'todolist:index' %}" class="text-light text-decoration-none">
										Back to Tasks
									</a>
								</button>
							</div>
						</div>						
					</div>
				</div>
			</div>
		</div>
	</div>
</div>
{% endblock %}

Activity/todolist/templates/todolist/update_task.html
{% extends 'base.html' %}

{% block title %}Login{% endblock %}

{% block content %}
	{% if user.is_anonymous == False %}
	<div class="container">
		<div class="row">
			<div class="col-6 offset-3">
				<h1 class="text-center my-3">Add A Task</h1>
				{% if error == True %}
					<p class="text-danger">Duplicate task found</p>
				{% endif %}
				<form action="{% url 'todolist:update_task' %}" method="post">
					{% csrf_token %}

					<div class="mb-3">
						<label for="task_name">Task Name: </label>
						<input class="form-control" id="task_name" type="text" name="task_name" value="{{ task_name }}" maxlength="50" required>
					</div>

					<div class="mb-3">
						<label for="description">Description: </label>
						<textarea class="form-control" name="description" required>{{ description }}</textarea>
					</div>

					<div class="mb-3">
						<label for="status">Status: </label>
						<input class="form-control" id="status" type="text" name="status" value="{{ status }}" maxlength="50" required>
					</div>

					<div class="text-center">
						<input class="btn btn-success" type="submit" value="Update Task">
					</div>
				</form>
			</div>
		</div>	
	</div>
	{% else %}
		<h1 class="text-center my-3">You are not authorized to access this page.</h1>
		<p class="text-center">Kindly login<a href="{% url 'todolist:login' %}">here</a></p>
	{% endif %}
{% endblock %}